StudentManagementSystem/ViewModels/AddGradeViewModel.cs
using StudentManagementSystem.Lib.Models;
using System.ComponentModel.DataAnnotations;

namespace StudentManagementSystem.WEB.ViewModels
{
    public class AddGradeViewModel
    {
        public int Id { get; set; }


        public int CourseId { get; set; }


        public int StudentId { get; set; }


        [Required(ErrorMessage ="Please select a grade!")]
        public Grade? Grade { get; set; }


        [Display(Name = "Course")]
        public string? CourseTitle { get; set; }


        [Display(Name = "Student")]
        public string? StudentName { get; set; }

        public Student? Student { get; set; }


        public Course? Course { get; set; }
    }
}

StudentManagementSystem/Controllers/EnrollmentsController.cs
using EnrollmentManagementSystem.BLL.Interfaces;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using StudentManagementSystem.BLL.Interfaces;
using StudentManagementSystem.WEB.ViewModels;

namespace StudentManagementSystem.WEB.Controllers
{
    public class EnrollmentsController : Controller
    {
        private readonly IEnrollmentRepository _enrollmentRepository;
        private readonly IStudentRepository _studentRepository;
        private readonly ICourseRepository _courseRepository;

        public EnrollmentsController(IEnrollmentRepository enrollmentRepository, IStudentRepository studentRepository, ICourseRepository courseRepository)
        {
            _enrollmentRepository = enrollmentRepository;
            _studentRepository = studentRepository;
            _courseRepository = courseRepository;
        }


        // GET: EnrollmentController
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            IList<Enrollment> enrollments = await _enrollmentRepository.GetAllEnrollments();
            return View(enrollments);
        }


        // GET: EnrollmentController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }



        // GET: EnrollmentController/Details/5
        [HttpGet]
        public async Task<ActionResult> AddGrade(int id)
        {
            Enrollment enrollment = await _enrollmentRepository.GetEnrollment(id);
            AddGradeViewModel addGradeVM = new AddGradeViewModel()
            {
                Id = enrollment.ID,
                CourseId = enrollment.CourseID,
                StudentId = enrollment.StudentID,
                CourseTitle = enrollment.Course.Title,
                StudentName = $"{enrollment.Student.FirstName} {enrollment.Student.LastName}",
                Grade = enrollment.Grade,
            };
            return View(addGradeVM);
        }


        [HttpPost]
        public async Task<ActionResult> AddGrade(AddGradeViewModel addGradeVM)
        {
            Enrollment enrollment = new Enrollment()
            {
                ID = addGradeVM.Id,
                CourseID = addGradeVM.CourseId,
                StudentID = addGradeVM.StudentId,
                Grade = addGradeVM.Grade
            };

            await _enrollmentRepository.UpdateEnrollment(enrollment);

            return RedirectToAction("Index", "Enrollments");
        }


        // GET: EnrollmentController/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            ViewData["Students"] = (await _studentRepository.GetAllStudents())
                .Select(s => new SelectListItem { Text = $"{s.FirstName} {s.LastName}", Value = s.Id.ToString()});

            ViewData["Courses"] = (await _courseRepository.GetAllCourses())
                .Select(c => new SelectListItem { Text = c.Title, Value = c.Id.ToString()});
            
            return View();
        }


        // POST: EnrollmentController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateEnrollmentViewModel createEnrollmentVM)
        {
            try
            {
                if(!ModelState.IsValid)
                {
                    return View();
                }

                Enrollment enrollment = new Enrollment()
                {
                    CourseID = createEnrollmentVM.CourseID.Value,
                    StudentID = createEnrollmentVM.StudentID.Value,
                    Grade = createEnrollmentVM.Grade
                };

                await _enrollmentRepository.AddEnrollment(enrollment);

                return RedirectToAction("Index", "Enrollments");
            }
            catch
            {
                return View();
            }
        }


        // GET: EnrollmentController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }


        // POST: EnrollmentController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }


        // GET: EnrollmentController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }


        // POST: EnrollmentController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

StudentManagementSystem/ViewComponents/CourseCountViewComponent.cs
using EnrollmentManagementSystem.BLL.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace StudentManagementSystem.WEB.ViewComponents
{
    public class CourseCountViewComponent : ViewComponent
    {
        private readonly IEnrollmentRepository _enrollmentRepository;

        public CourseCountViewComponent(IEnrollmentRepository enrollmentRepository)
        {
            _enrollmentRepository = enrollmentRepository;
        }

        public async Task<IViewComponentResult> InvokeAsync(string title = null)
        {
            var result = await _enrollmentRepository.CourseEnrollmentCounts(title);

            return View(result);
        }
    }
}

StudentManagementSystem/Views/Enrollments/AddGrade.cshtml
@model AddGradeViewModel

@{
    ViewData["Title"] = "Add Grade";
}

<form method="post" asp-controller="Enrollments" asp-action="AddGrade">

    <input asp-for="Id" hidden />
    <input asp-for="CourseId" hidden />
    <input asp-for="StudentId" hidden />

    <div class="row mb-3 mt-3">
        <label asp-for="CourseTitle" class="col-form-label col-md-2"></label>
        <div class="col-md-6">
            <input asp-for="CourseTitle" class="form-control" readonly/>
        </div>
    </div>

    <div class="row">
        <label asp-for="StudentName" class="col-form-label col-md-2"></label>
        <div class="col-md-6">
            <input asp-for="StudentName" class="form-control" readonly />
        </div>
    </div>

    <div class="row mb-3">
        <label asp-for="Grade" class="col-form-label col-md-2"></label>
        <div class="col-md-6">
            <select asp-for="Grade" class="form-control form-select" asp-items="@Html.GetEnumSelectList<Grade>()">
                <option value="">Select Grade</option>
            </select>
            <span asp-validation-for="Grade" class="text-danger"></span>
        </div>
    </div>

    <div class="row">
        <button type="submit" class="btn btn-primary col-md-1 me-1">Add Grade</button>
        <a asp-controller="Enrollments" asp-action="Index" class="btn btn-secondary col-md-1">Cancel</a>
    </div>
</form>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

StudentManagementSystem/Views/Enrollments/Create.cshtml
@model CreateEnrollmentViewModel

@{
    ViewData["Title"] = "Create Enrollment";
}

<h3 class="text-center fw-bold">Create a new Enrollment</h3>

<form method="post" asp-controller="Enrollments" asp-action="Create">

    <div class="row mb-3 mt-3">
        <label asp-for="CourseID" class="col-form-label col-md-2"></label>
        <div class="col-md-6">
            <select asp-for="CourseID" class="form-control form-select" asp-items="@ViewBag.Courses">
                <option value="">Select the Course</option>
            </select>
            <span asp-validation-for="CourseID" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-3 mt-3">
        <label asp-for="StudentID" class="col-form-label col-md-2"></label>
        <div class="col-md-6">
            <select asp-for="StudentID" class="form-control form-select" asp-items="@ViewBag.Students">
                <option value="">Select the Student</option>
            </select>
            <span asp-validation-for="StudentID" class="text-danger"></span>
        </div>
    </div>

    <div class="row mb-3 mt-3">
        <label asp-for="Grade" class="col-form-label col-md-2"></label>
        <div class="col-md-6">
            <select asp-for="Grade" class="form-control form-select" asp-items="@Html.GetEnumSelectList<Grade>()">
                <option value="">Select a Grade</option>
            </select>
        </div>
    </div>

    <div class="row">
        <button type="submit" class="btn btn-primary col-md-1 me-1">Create</button>
        <a asp-controller="Enrollments" asp-action="Index" class="btn btn-secondary col-md-1">Cancel</a>
    </div>

</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

StudentManagementSystem/Views/Enrollments/Index.cshtml
@model IList<Enrollment>

@{
    ViewData["Title"] = "Enrollment List";
}

<a asp-controller="Enrollments" asp-action="Create" class="btn btn-primary mb-3">Create Enrollment</a>

@* <div>
    @await Component.InvokeAsync("CourseCount")

</div> *@

<vc:course-count></vc:course-count>

<table class="table table-borderless table-responsive table-striped">
    <thead>
        <tr>
            <th>Course</th>
            <th>Student</th>
            <th>Grade</th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        @foreach(var enrollment in Model)
        {
            <tr>
                <td>@enrollment.Course.Title</td>
                <td>@($"{ enrollment.Student.FirstName } { enrollment.Student.FirstName }")</td>
                <td>@(!enrollment.Grade.HasValue ? "No Grade" : enrollment.Grade)</td>
                @if (!enrollment.Grade.HasValue)
                {
                    <td>
                        <a asp-controller="Enrollments" asp-action="AddGrade" asp-route-id="@enrollment.ID" class="btn btn-primary">Add Grade</a>
                    </td>

                }
                else
                {
                    <td>
                        <button type="button" class="btn btn-primary" disabled>Add Grade</button>
                    </td>
                }
            </tr>
        }
    </tbody>
</table>